server:
  port: 8081


spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # manager_system
    url: jdbc:mysql://localhost:3306/manager_system?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 5
  jackson:
    default-property-inclusion: non_null
  mvc:
    dispatch-options-request: true

mybatis-plus:
  type-aliases-package: edu.f4.pojo
#  type-enums-package:

logging:
   level:
     edu.f4: debug

ai:
  appId: 27752402
  apiKey: z7otDrIMALONLdbtlpp2xO3i
  secretKey: 1fq1WAeENGAkdG197apl6bEw3DQrzaaC
  imageType: BASE64
  groupId: user_face

face:
  url: http://localhost:8080/#/facelogin